version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - server
    command: python client_file.py /app/data 20  # Adjust command to run your script
    volumes:
      - ./data:/app/data
