name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: |
            ~/.docker/cache

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d

      - name: Run tests
        run: |
          # Assuming client tests are part of the client container
          docker-compose exec client pytest

      - name: Stop and remove containers
        run: |
          docker-compose down

