name: CI

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: latest


    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Run inventory service
      run: |
        docker-compose up -d

    - name: Run E2E tests
      run: |
        docker build --target test -t inventory-test .
        docker run --rm inventory-test

    - name: Stop Docker containers
      run: |
        docker-compose down

